### ISSUE TITLE
Errors in Kirby 3.8.3

### ISSUE THREAD

**Issue by MikeHarrison** [rasteiner/conditionalblocks#4]
Hi,

I have updated a site using Conditional Blocks to Kirby 3.8.3, and am getting some console errors in the panel caused by the plugin:

`TypeError: cannot use 'in' operator to search for "default" in "constraints"`
`Uncaught TypeError: this.$el is undefined`

Happy to provide any additional info if needed

**Comment by rasteiner** [comment]
Thanks for the notice. :)
Looks like something in Vue changed between Kirby releases.

Version 0.0.3 should work in kirby 3.8

**Comment by MikeHarrison** [comment]
Hi - I have just updated and this fixes the issue. Thanks for the quick response and quick fix :)
